joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    topic: joint_states
    
joint_group_pos_controller:
    type: position_controllers/JointGroupPositionController
    joints:
        - sdh_knuckle_joint
        - sdh_thumb_2_joint
        - sdh_thumb_3_joint
        - sdh_finger_12_joint
        - sdh_finger_13_joint
        - sdh_finger_21_joint
        - sdh_finger_22_joint
        - sdh_finger_23_joint
            
# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
pos_based_pos_traj_controller:
    type: position_controllers/JointTrajectoryController
    joints:
        - sdh_knuckle_joint
        - sdh_thumb_2_joint
        - sdh_thumb_3_joint
        - sdh_finger_12_joint
        - sdh_finger_13_joint
        - sdh_finger_21_joint
        - sdh_finger_22_joint
        - sdh_finger_23_joint
    
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        sdh_knuckle_joint: {trajectory: 0.1, goal: 0.1}
        sdh_thumb_2_joint: {trajectory: 0.1, goal: 0.1}
        sdh_thumb_3_joint: {trajectory: 0.1, goal: 0.1}
        sdh_finger_12_joint: {trajectory: 0.1, goal: 0.1}
        sdh_finger_13_joint: {trajectory: 0.1, goal: 0.1}
        sdh_finger_21_joint: {trajectory: 0.1, goal: 0.1}
        sdh_finger_22_joint: {trajectory: 0.1, goal: 0.1}
        sdh_finger_23_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  50
    action_monitor_rate: 10

        
joint_group_vel_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
        - sdh_knuckle_joint
        - sdh_thumb_2_joint
        - sdh_thumb_3_joint
        - sdh_finger_12_joint
        - sdh_finger_13_joint
        - sdh_finger_21_joint
        - sdh_finger_22_joint
        - sdh_finger_23_joint
